INSERT INTO authorised_value_categories (category_name) VALUES ('RDACARRIER');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDACARRIER', 'audio cartridge', 'audio cartridge', 'audio cartridge'),
('RDACARRIER', 'audio belt', 'audio belt', 'audio belt'),
('RDACARRIER', 'audio cylinder', 'audio cylinder', 'audio cylinder'),
('RDACARRIER', 'audio disc', 'audio disc', 'audio disc'),
('RDACARRIER', 'sound track reel', 'sound track reel', 'sound track reel'),
('RDACARRIER', 'audio roll', 'audio roll', 'audio roll'),
('RDACARRIER', 'audio wire reel', 'audio wire reel', 'audio wire reel'),
('RDACARRIER', 'audiocassette', 'audiocassette', 'audiocassette'),
('RDACARRIER', 'audiotape reel', 'audiotape reel', 'audiotape reel'),
('RDACARRIER', 'computer card', 'computer card', 'computer card'),
('RDACARRIER', 'computer chip cartridge', 'computer chip cartridge', 'computer chip cartridge'),
('RDACARRIER', 'computer disc', 'computer disc', 'computer disc'),
('RDACARRIER', 'computer disc cartridge', 'computer disc cartridge', 'computer disc cartridge'),
('RDACARRIER', 'computer tape cartridge', 'computer tape cartridge', 'computer tape cartridge'),
('RDACARRIER', 'computer tape cassette', 'computer tape cassette', 'computer tape cassette'),
('RDACARRIER', 'computer tape reel', 'computer tape reel', 'computer tape reel'),
('RDACARRIER', 'online resource', 'online resource', 'online resource'),
('RDACARRIER', 'aperture card', 'aperture card', 'aperture card'),
('RDACARRIER', 'microfiche', 'microfiche', 'microfiche'),
('RDACARRIER', 'microfiche cassette', 'microfiche cassette', 'microfiche cassette'),
('RDACARRIER', 'microfilm cartridge', 'microfilm cartridge', 'microfilm cartridge'),
('RDACARRIER', 'microfilm cassette', 'microfilm cassette', 'microfilm cassette'),
('RDACARRIER', 'microfilm reel', 'microfilm reel', 'microfilm reel'),
('RDACARRIER', 'microfilm roll', 'microfilm roll', 'microfilm roll'),
('RDACARRIER', 'microfilm slip', 'microfilm slip', 'microfilm slip'),
('RDACARRIER', 'microopaque', 'microopaque', 'microopaque'),
('RDACARRIER', 'microscope slide', 'microscope slide', 'microscope slide'),
('RDACARRIER', 'film cartridge', 'film cartridge', 'film cartridge'),
('RDACARRIER', 'film cassette', 'film cassette', 'film cassette'),
('RDACARRIER', 'film reel', 'film reel', 'film reel'),
('RDACARRIER', 'film roll', 'film roll', 'film roll'),
('RDACARRIER', 'filmslip', 'filmslip', 'filmslip'),
('RDACARRIER', 'filmstrip', 'filmstrip', 'filmstrip'),
('RDACARRIER', 'filmstrip cartridge', 'filmstrip cartridge', 'filmstrip cartridge'),
('RDACARRIER', 'overhead transparency', 'overhead transparency', 'overhead transparency'),
('RDACARRIER', 'slide', 'slide', 'slide'),
('RDACARRIER', 'stereograph card', 'stereograph card', 'stereograph card'),
('RDACARRIER', 'stereograph disc', 'stereograph disc', 'stereograph disc'),
('RDACARRIER', 'card', 'card', 'card'),
('RDACARRIER', 'flipchart', 'flipchart', 'flipchart'),
('RDACARRIER', 'roll', 'roll', 'roll'),
('RDACARRIER', 'sheet', 'sheet', 'sheet'),
('RDACARRIER', 'volume', 'volume', 'volume'),
('RDACARRIER', 'object', 'object', 'object'),
('RDACARRIER', 'video cartridge', 'video cartridge', 'video cartridge'),
('RDACARRIER', 'videocassette', 'videocassette', 'videocassette'),
('RDACARRIER', 'videodisc', 'videodisc', 'videodisc'),
('RDACARRIER', 'videotape reel', 'videotape reel', 'videotape reel'),
('RDACARRIER', 'unspecified', 'unspecified', 'unspecified'),
('RDACARRIER', 'other', 'other', 'other');
INSERT INTO authorised_value_categories (category_name) VALUES ('RDACARRIER_CODE');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDACARRIER_CODE', 'sg', 'audio cartridge', 'audio cartridge'),
('RDACARRIER_CODE', 'sb', 'audio belt', 'audio belt'),
('RDACARRIER_CODE', 'se', 'audio cylinder', 'audio cylinder'),
('RDACARRIER_CODE', 'sd', 'audio disc', 'audio disc'),
('RDACARRIER_CODE', 'si', 'sound track reel', 'sound track reel'),
('RDACARRIER_CODE', 'sq', 'audio roll', 'audio roll'),
('RDACARRIER_CODE', 'sw', 'audio wire reel', 'audio wire reel'),
('RDACARRIER_CODE', 'ss', 'audiocassette', 'audiocassette'),
('RDACARRIER_CODE', 'st', 'audiotape reel', 'audiotape reel'),
('RDACARRIER_CODE', 'sz', 'other (audio)', 'other (audio)'),
('RDACARRIER_CODE', 'ck', 'computer card', 'computer card'),
('RDACARRIER_CODE', 'cb', 'computer chip cartridge', 'computer chip cartridge'),
('RDACARRIER_CODE', 'cd', 'computer disc', 'computer disc'),
('RDACARRIER_CODE', 'ce', 'computer disc cartridge', 'computer disc cartridge'),
('RDACARRIER_CODE', 'ca', 'computer tape cartridge', 'computer tape cartridge'),
('RDACARRIER_CODE', 'cf', 'computer tape cassette', 'computer tape cassette'),
('RDACARRIER_CODE', 'ch', 'computer tape reel', 'computer tape reel'),
('RDACARRIER_CODE', 'cr', 'online resource', 'online resource'),
('RDACARRIER_CODE', 'cz', 'other (computer)', 'other (computer)'),
('RDACARRIER_CODE', 'ha', 'aperture card', 'aperture card'),
('RDACARRIER_CODE', 'he', 'microfiche', 'microfiche'),
('RDACARRIER_CODE', 'hf', 'microfiche cassette', 'microfiche cassette'),
('RDACARRIER_CODE', 'hb', 'microfilm cartridge', 'microfilm cartridge'),
('RDACARRIER_CODE', 'hc', 'microfilm cassette', 'microfilm cassette'),
('RDACARRIER_CODE', 'hd', 'microfilm reel', 'microfilm reel'),
('RDACARRIER_CODE', 'hj', 'microfilm roll', 'microfilm roll'),
('RDACARRIER_CODE', 'hh', 'microfilm slip', 'microfilm slip'),
('RDACARRIER_CODE', 'hg', 'microopaque', 'microopaque'),
('RDACARRIER_CODE', 'hz', 'other (microform)', 'other (microform)'),
('RDACARRIER_CODE', 'pp', 'microscope slide', 'microscope slide'),
('RDACARRIER_CODE', 'pz', 'other (microscopic)', 'other (microscopic)'),
('RDACARRIER_CODE', 'mc', 'film cartridge', 'film cartridge'),
('RDACARRIER_CODE', 'mf', 'film cassette', 'film cassette'),
('RDACARRIER_CODE', 'mr', 'film reel', 'film reel'),
('RDACARRIER_CODE', 'mo', 'film roll', 'film roll'),
('RDACARRIER_CODE', 'gd', 'filmslip', 'filmslip'),
('RDACARRIER_CODE', 'gf', 'filmstrip', 'filmstrip'),
('RDACARRIER_CODE', 'gc', 'filmstrip cartridge', 'filmstrip cartridge'),
('RDACARRIER_CODE', 'gt', 'overhead transparency', 'overhead transparency'),
('RDACARRIER_CODE', 'gs', 'slide', 'slide'),
('RDACARRIER_CODE', 'mz', 'other (projected image)', 'other (projected image)'),
('RDACARRIER_CODE', 'eh', 'stereograph card', 'stereograph card'),
('RDACARRIER_CODE', 'es', 'stereograph disc', 'stereograph disc'),
('RDACARRIER_CODE', 'ez', 'other (stereographic carriers)', 'other (stereographic carriers)'),
('RDACARRIER_CODE', 'no', 'card', 'card'),
('RDACARRIER_CODE', 'nn', 'flipchart', 'flipchart'),
('RDACARRIER_CODE', 'na', 'roll', 'roll'),
('RDACARRIER_CODE', 'nb', 'sheet', 'sheet'),
('RDACARRIER_CODE', 'nc', 'volume', 'volume'),
('RDACARRIER_CODE', 'nr', 'object', 'object'),
('RDACARRIER_CODE', 'nz', 'other (unmediated)', 'other (unmediated)'),
('RDACARRIER_CODE', 'vc', 'video cartridge', 'video cartridge'),
('RDACARRIER_CODE', 'vf', 'videocassette', 'videocassette'),
('RDACARRIER_CODE', 'vd', 'videodisc', 'videodisc'),
('RDACARRIER_CODE', 'vr', 'videotape reel', 'videotape reel'),
('RDACARRIER_CODE', 'vz', 'other (video)', 'other (video)'),
('RDACARRIER_CODE', 'zu', 'unspecified', 'unspecified');
INSERT INTO authorised_value_categories (category_name) VALUES ('RDACONTENT');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDACONTENT', 'cartographic dataset', 'cartographic dataset', 'cartographic dataset'),
('RDACONTENT', 'cartographic image', 'cartographic image', 'cartographic image'),
('RDACONTENT', 'cartographic moving image', 'cartographic moving image', 'cartographic moving image'),
('RDACONTENT', 'cartographic tactile image', 'cartographic tactile image', 'cartographic tactile image'),
('RDACONTENT', 'cartographic tactile three-dimensional form', 'cartographic tactile three-dimensional form', 'cartographic tactile three-dimensional form'),
('RDACONTENT', 'cartographic three-dimensional form', 'cartographic three-dimensional form', 'cartographic three-dimensional form'),
('RDACONTENT', 'computer dataset', 'computer dataset', 'computer dataset'),
('RDACONTENT', 'computer program', 'computer program', 'computer program'),
('RDACONTENT', 'notated movement', 'notated movement', 'notated movement'),
('RDACONTENT', 'notated music', 'notated music', 'notated music'),
('RDACONTENT', 'performed music', 'performed music', 'performed music'),
('RDACONTENT', 'sounds', 'sounds', 'sounds'),
('RDACONTENT', 'spoken word', 'spoken word', 'spoken word'),
('RDACONTENT', 'still image', 'still image', 'still image'),
('RDACONTENT', 'tactile image', 'tactile image', 'tactile image'),
('RDACONTENT', 'tactile notated music', 'tactile notated music', 'tactile notated music'),
('RDACONTENT', 'tactile notated movement', 'tactile notated movement', 'tactile notated movement'),
('RDACONTENT', 'tactile text', 'tactile text', 'tactile text'),
('RDACONTENT', 'tactile three-dimensional form', 'tactile three-dimensional form', 'tactile three-dimensional form'),
('RDACONTENT', 'text', 'text', 'text'),
('RDACONTENT', 'three-dimensional form', 'three-dimensional form', 'three-dimensional form'),
('RDACONTENT', 'three-dimensional moving image', 'three-dimensional moving image', 'three-dimensional moving image'),
('RDACONTENT', 'two-dimensional moving image', 'two-dimensional moving image', 'two-dimensional moving image'),
('RDACONTENT', 'other', 'other', 'other'),
('RDACONTENT', 'unspecified', 'unspecified', 'unspecified');
INSERT INTO authorised_value_categories (category_name) VALUES ('RDACONTENT_CODE');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDACONTENT_CODE', 'crd', 'cartographic dataset', 'cartographic dataset'),
('RDACONTENT_CODE', 'cri', 'cartographic image', 'cartographic image'),
('RDACONTENT_CODE', 'crm', 'cartographic moving image', 'cartographic moving image'),
('RDACONTENT_CODE', 'crt', 'cartographic tactile image', 'cartographic tactile image'),
('RDACONTENT_CODE', 'crn', 'cartographic tactile three-dimensional form', 'cartographic tactile three-dimensional form'),
('RDACONTENT_CODE', 'crf', 'cartographic three-dimensional form', 'cartographic three-dimensional form'),
('RDACONTENT_CODE', 'cod', 'computer dataset', 'computer dataset'),
('RDACONTENT_CODE', 'cop', 'computer program', 'computer program'),
('RDACONTENT_CODE', 'ntv', 'notated movement', 'notated movement'),
('RDACONTENT_CODE', 'ntm', 'notated music', 'notated music'),
('RDACONTENT_CODE', 'prm', 'performed music', 'performed music'),
('RDACONTENT_CODE', 'snd', 'sounds', 'sounds'),
('RDACONTENT_CODE', 'spw', 'spoken word', 'spoken word'),
('RDACONTENT_CODE', 'sti', 'still image', 'still image'),
('RDACONTENT_CODE', 'tci', 'tactile image', 'tactile image'),
('RDACONTENT_CODE', 'tcm', 'tactile notated music', 'tactile notated music'),
('RDACONTENT_CODE', 'tcn', 'tactile notated movement', 'tactile notated movement'),
('RDACONTENT_CODE', 'tct', 'tactile text', 'tactile text'),
('RDACONTENT_CODE', 'tcf', 'tactile three-dimensional form', 'tactile three-dimensional form'),
('RDACONTENT_CODE', 'txt', 'text', 'text'),
('RDACONTENT_CODE', 'tdf', 'three-dimensional form', 'three-dimensional form'),
('RDACONTENT_CODE', 'tdm', 'three-dimensional moving image', 'three-dimensional moving image'),
('RDACONTENT_CODE', 'tdi', 'two-dimensional moving image', 'two-dimensional moving image'),
('RDACONTENT_CODE', 'xxx', 'other', 'other'),
('RDACONTENT_CODE', 'zzz', 'unspecified', 'unspecified');
INSERT INTO authorised_value_categories (category_name) VALUES ('RDAMEDIA');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDAMEDIA', 'audio', 'audio', 'audio'),
('RDAMEDIA', 'computer', 'computer', 'computer'),
('RDAMEDIA', 'microform', 'microform', 'microform'),
('RDAMEDIA', 'microscopic', 'microscopic', 'microscopic'),
('RDAMEDIA', 'projected', 'projected', 'projected'),
('RDAMEDIA', 'stereographic', 'stereographic', 'stereographic'),
('RDAMEDIA', 'unmediated', 'unmediated', 'unmediated'),
('RDAMEDIA', 'video', 'video', 'video'),
('RDAMEDIA', 'other', 'other', 'other'),
('RDAMEDIA', 'unspecified', 'unspecified', 'unspecified');
INSERT INTO authorised_value_categories (category_name) VALUES ('RDAMEDIA_CODE');
INSERT INTO authorised_values (category, authorised_value, lib, lib_opac)
VALUES ('RDAMEDIA_CODE', 's', 'audio', 'audio'),
('RDAMEDIA_CODE', 'c', 'computer', 'computer'),
('RDAMEDIA_CODE', 'h', 'microform', 'microform'),
('RDAMEDIA_CODE', 'p', 'microscopic', 'microscopic'),
('RDAMEDIA_CODE', 'g', 'projected', 'projected'),
('RDAMEDIA_CODE', 'e', 'stereographic', 'stereographic'),
('RDAMEDIA_CODE', 'n', 'unmediated', 'unmediated'),
('RDAMEDIA_CODE', 'v', 'video', 'video'),
('RDAMEDIA_CODE', 'x', 'other', 'other'),
('RDAMEDIA_CODE', 'z', 'unspecified', 'unspecified');
 Wrote koha.sql file
